"""empty message

Revision ID: 247411a1c00a
Revises: 330c391ded0a
Create Date: 2013-08-10 18:01:59.587943

"""

# revision identifiers, used by Alembic.
revision = '247411a1c00a'
down_revision = '330c391ded0a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.alter_column(u'weather_forecast', u'temp',
               existing_type=mysql.FLOAT(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'weather_forecast', u'temp',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.drop_table('settings')
    ### end Alembic commands ###
