#!/bin/sh

exit 0

# run every 10 min

echo "#00:13:8f:62:ff:01" > /var/log/narodmon
/usr/bin/digitemp_DS9097 -c /root/.digitemprc -t 0 -s /dev/ttyUSB0 -q -i | awk '{FS=" "; if($2==":") { mac[NR-1]=$1;}; if($4=="Sensor") { print "#"mac[$5]"#"$7;}}' >> /var/log/narodmon
echo "##" >> /var/log/narodmon
LC=`cat /var/log/narodmon | wc -l`
if [ $LC -gt 2 ]
 then cat /var/log/narodmon | nc narodmon.ru 8283 > /var/log/narodmon.log
fi
