#!/bin/bash

# convert any video files in current directory to 

dumba() {

orig=`du -b orig | awk {'print $1'}`
code=`du -b code | awk {'print $1'}`
perc=`echo "100-(($code*100)/$orig)" | bc`

echo "$perc% compressed" | figlet
echo "original is $orig, compressed is $code, compression $perc%"

}

# to cut
# ffmpeg -i filer.mp4 -ss 01:24:22 -t 00:09:30 -async 1 -strict -2 -vn -filter:a dynaudnorm 1.spx

# exit on error
set -e

# extended globbing
shopt -s extglob
shopt -s nullglob

# video files
videos=*(*.mp3|*.MOV|*.amr|*.ogg|*.aac|*.wma|*.WMA|*.flv|*.mp4|*.avi|*.mkv|*.wav|*.m4a|*.m4v|*.webm|*.wmv|*.3gp|*.3GP|*.MP4|*.mov|*.ts|*.MKV)

# grab convert

for file in $videos; do
    cowsay -d "$file convert"

    mkdir -p code
    mkdir -p orig

    case $1 in
        "mp3")		echo "mp3 coding" | figlet; 
			outputname="code/${file%.*}.mp3";
			ffmpeg -i "$file" -vn -acodec libmp3lame -ab 128k -ar 44100 -ac 1 -f mp3 -filter:a dynaudnorm "$outputname";;
        "wav")		echo "wav decoding" | figlet; 
			outputname="code/${file%.*}.wav";
			ffmpeg -i "$file" "$outputname";;
        "spex")		echo "spex coding" | figlet;
        		outputname="code/${file%.*}.spx";
			ffmpeg -hide_banner -i "$file" -vn -filter:a dynaudnorm "$outputname";;
        "supra")	echo "supra coding" | figlet;
        		outputname="code/${file%.*}.mp4";
			ffmpeg -hide_banner -i "$file" -s 640x480 -acodec libmp3lame -ar 44100 -ab 128k -ac 1 -filter:a dynaudnorm "$outputname";;
        "q415")		echo "q415" | figlet;
        		outputname="code/${file%.*}.mp4";
			ffmpeg -hide_banner -i "$file" -s 854x480 -acodec libmp3lame -ar 44100 -ab 128k -ac 1 -filter:a dynaudnorm "$outputname";;
        "mp4")		echo "mp4 recoding" | figlet;
        		outputname="code/${file%.*}.mp4";
			ffmpeg -hide_banner -i "$file" -filter:a dynaudnorm "$outputname";;
	"golos")	echo "golos recoding" | figlet;
        		outputname="code/${file%.*}.mp3";
			ffmpeg -hide_banner -i "$file" -af dynaudnorm "$outputname";;
    esac

    mv "$file" "orig/"

    chmod -R 777 code
    chmod -R 777 orig

    dumba;

done

echo "all done!" | cowsay -d
dumba;

sync
